### ISSUE TITLE
pick up pistol it duplicate

### ISSUE THREAD

**Issue by Sh1r0ko465** [mickromash/MR_NotSoHideousAnimations#3]
fist sorry for my bad english but when i pick up an pistol or the revolver. it wiil have two pistol in my pocket. i use the newest gzdoom 4.14.2 with hd-4.14.2c and i try orginal hd-4.14.2c without mod it will work well with no duplicate.

<img width="3840" height="2160" alt="Image" src="https://github.com/user-attachments/assets/7bbcf3b9-52df-4c75-ae27-efd4bd9a143f" />

**Comment by mickromash** [comment]
Thanks for the feedback, it should be fixed now

**Comment by Sh1r0ko465** [comment]
i download the new version but it still duplicate my pistol and revolver

**Comment by mickromash** [comment]
It doesn't happen to me. Have tried running it without other add-ons?

**Comment by Sh1r0ko465** [comment]
sure. i only use MR_NotSoHideousAnimations-master.zip with hd-4.14.2c.pk7 and it still duplicate pistol and revolver i even try to use another version of gzdoom 4.14.1 with hd-4.14.1a.pk7+MR_NotSoHideousAnimations-master.zip. it still have this bug i dont know why

**Comment by mickromash** [comment]
Maybe you should try redownloading the mod, because I can't spot the handguns duplication anymore

**Comment by Sh1r0ko465** [comment]
Maybe you should download your github version with hd-4.14.2c and try it on gzdoom 4.14.2 of course i download the newest the master version of this mod try it with 2 version of gzdoom and 2 version of hd. i just dont know what should i do it just duplication my pistol pick up one it just give me two. is my hd version problem? or the setting? or the gzdoom version problem? i dont know

**Comment by mickromash** [comment]
I actually did download the github build multiple times already, and it works fine, so I honestly got no idea why you still got this issue

**Comment by Sh1r0ko465** [comment]
https://streamable.com/jtwfm2 this is a video i download an new hd and gzdoom with your mod you can see it. it just weird

**Comment by mickromash** [comment]
Ok, I finally managed to encounter the duplication by constantly dropping and picking up the pistol, I'm gonna try fixing it again

**Comment by mickromash** [comment]
So, I figured out a fix, but it won't be possible to pick up the weapon right after you dropped it

**Comment by Sh1r0ko465** [comment]
yes it is fixed thanks. your mod is awesome

**Comment by Sh1r0ko465** [comment]
and it has another issues i have been found. in multiplayer you cant use stimpack for another players. but we have a lot of mod play with this mod. i will try that for next week

**Comment by mickromash** [comment]
It's fixed now. Thanks for your help!
